### ISSUE TITLE
Infrequent crash when customizing house

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#100]
Server: OSI
Client version: 7.0.83.27
Build: 2020-01-19

Encountered a crash once when starting house customization. Stack trace:

Orion version is: 1.0.0.0 (build Jan 19 2020 00:29:27) x64 bit
Unhandled exception #1: 0xC0000094 at 00007FF605A29D81
SymInit: Symbol-SearchPath: '.;C:\Orion Launcher;C:\Orion Launcher\OA;C:\Orion Launcher;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Name'
Windows version: 10.0.18362
d:\orionuo_project\orionuo_sdl\orionuo\managers\packetmanager.cpp (5844): CPacketManager::HandleCustomHouse
d:\orionuo_project\orionuo_sdl\orionuo\managers\packetmanager.cpp (792): CPacketManager::OnPacket
d:\orionuo_project\orionuo_sdl\orionuo\network\packetreader.cpp (51): CPacketReader::Read
d:\orionuo_project\orionuo_sdl\orionuo\renderer\renderer.cpp (1996): CRenderer::ProcessRendering
d:\orionuo_project\orionuo_sdl\orionuo\orionapplication.cpp (1086): COrionApplication::Execute
d:\orionuo_project\orionuo_sdl\orionuo\main.cpp (90): <lambda_937c0d271b95921c060a833bfd73fcb8>::operator()
c:\qt\5.10.0\msvc2015_64\include\qtconcurrent\qtconcurrentrunbase.h (136): QtConcurrent::RunFunctionTask<void>::run
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000000707C4D27)
00000000707C4D27 (Qt5Core): (filename not available): QThreadPoolPrivate::reset
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000000707C862B)
00000000707C862B (Qt5Core): (filename not available): QThread::start
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFE54157BD4)
00007FFE54157BD4 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFE55DECED1)
00007FFE55DECED1 (ntdll): (filename not available): RtlUserThreadStart

**Comment by Hotride** [comment]
Fixed, thanks you!
