### ISSUE TITLE
Duplicate 'My name's color' option

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#103]
Server: OSI
Client version: 7.0.83.27
Build: 2020-01-19

1. Login with a character.
2. Open the options.
3. Select the chat menu.
4. Observe there are duplicate options for setting 'My name's color'

![issue_chat](https://user-images.githubusercontent.com/16568056/73127264-d2ed6a00-3f8b-11ea-8e6c-b37a22060f81.PNG)

**Comment by Hotride** [comment]
Fixed, thanks you!
