### ISSUE TITLE
Journal filter options are not retained after closing UO

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#105]
Server: OSI
Client: 7.0.83.27
Build: 2020-01-19

1. Launch server from Orion Launcher, login, and select a character.
2. Open your journal.
3. Uncheck one of the filter options: For example, Objects or Client.
4. Logout.
5. Close UO.
6. Relaunch server, login, and select a character.
7. Open your journal.
8. Observe filter options are not retained.

**Comment by Hotride** [comment]
Fixed, thanks you!
