### ISSUE TITLE
Orion Assistant - Typo in 'Turn' context menu item

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#107]
Server: OSI
Client: 7.0.83.27
Build: 2020-01-19

1. Open Orion Assistant
2. Open script editor
3. Right click to show context menu
4. Hover over 'Walker' menu item
5. Observe typo: 'Trun' should be 'Turn'

![typo_turn](https://user-images.githubusercontent.com/16568056/73142152-8bcdaa80-4059-11ea-9070-d111456c59fc.png)

**Comment by Hotride** [comment]
Fixed, thanks you!
