### ISSUE TITLE
Orion Assistant - Duplicate 'Ground' option in Globals context menu

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#108]
Server: OSI
Client: 7.0.83.27
Build: 2020-01-19

1. Open Orion Assistant
2. Open script editor
3. Right click to show context menu
4. Hover over 'Globals' menu item
5. Observe two 'Ground' menu items

![issue_ground](https://user-images.githubusercontent.com/16568056/73142201-10b8c400-405a-11ea-8d1e-eb34411f23eb.png)

**Comment by Hotride** [comment]
Fixed to ScriptName, thanks you!
