### ISSUE TITLE
Typo in 'Dont turn to combiant' menu option

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#109]
Server: OSI
Client: 7.0.83.27
Build: 2020-01-19

1. Open Options from your paperdoll.
2. Select the Orion Configuration menu (left side, second from the top).
3. Scroll down the menu options.
4. Observe there is a 'Dont turn to combiant' option. 'Combiant' should probably be 'combatant'.

![typo_combiant](https://user-images.githubusercontent.com/16568056/73142407-29c27480-405c-11ea-83c9-7c9ee5521b44.PNG)

**Comment by Hotride** [comment]
Fixed, thanks you!
