### ISSUE TITLE
Client don't refresh during speedMode

### ISSUE THREAD

**Issue by Jhobean** [Hotride/OrionUO#114]
# Information we need from you if you want to have something fixed:

There is a problem of "refresh" when some player use speedmode=1 (run fast like a horse)

https://media.discordapp.net/attachments/597989183818301441/682742114886615103/Ultima_Online_-_Phil_Cryptonite_85c_2020-02-27_19-12-33.mp4

Like you see on video, the character dissapear..

We try the same setting on original client and CrossUo (work well)

https://cdn.discordapp.com/attachments/597989183818301441/682770481035608134/Ultima_Online_-_Phil_Cryptonite_85c_2020-02-27_21-05-20.mp4

https://cdn.discordapp.com/attachments/597989183818301441/682771038114808020/Ultima_Online_-_Phil_Cryptonite_85c_2020-02-27_21-07-44.mp4

**Comment by Hotride** [comment]
FIxed, thanks you!
