### ISSUE TITLE
Locking the game window also locks gump resizing

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#117]
Server: OSI
Client: 7.0.85.14
Build: 1.0.0.0 (build Mar 28 2020 00:13:22) x64 bit

1. Enable grid mode for containers
2. Enable 'Lock game window moving and resizing'
3. Observe this also locks container resizing

Expected: Lock game window moving and resizing will only apply to the game window.

![issue_lock](https://user-images.githubusercontent.com/16568056/77812506-1e99be00-7078-11ea-9eac-561fa244c2a9.PNG)

**Comment by Hotride** [comment]
Yes, this option blocks resizing for the game window and the container gump with a grid and counter gump (if I not mistake).
Need to change its option name.
