### ISSUE TITLE
Orion Assistant - Crash when trying to indent all script lines

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#118]
Build: 1.0.0.0 (build Mar 28 2020 00:13:22) x64 bit

1. Go to Scripts
2. Open a Script
3. Press Ctrl + A to highlight all script lines
4. Press tab to try to indent the lines
5. Observe crash

Crash log isn't informative. It just has the build number.

![script_crash](https://user-images.githubusercontent.com/16568056/77826526-5c353000-70e6-11ea-9b92-ff0ff2ef18a2.gif)

**Comment by Hotride** [comment]
Will be fixed in next update.
