### ISSUE TITLE
Orion Assistant - Opening a different script does not update current script file path

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#120]
Orion version is: 1.0.0.0 (build Mar 28 2020 00:13:22) x64 bit

Precondition: You've already written a few scripts.

1. Go to Scripts
2. Observe default script is selected.
3. Open a different script.
4. Observe script path does not update: Any changes you save for this script will overwrite the previously selected script.

Expected: When you open a different script, the script path will update.

**Comment by Hotride** [comment]
Do you enter the path to another script manually, or use the path selection button?
When using the button, the path and script are correctly changed.

**Comment by calemccammon** [comment]
Hi @Hotride 

Gif attached. I am just using the Open button toward the top. My expectation is that this would update the path automatically. More than once, while opening and updating scripts, I found myself making changes to scripts that I didn't intend to.

![script_path](https://user-images.githubusercontent.com/16568056/77968967-98b78600-72b6-11ea-8456-66329af4066d.gif)

**Comment by Hotride** [comment]
Ah, ok, will be fixed in next update, thanks you!
