### ISSUE TITLE
Dupe from selected profile does nothing

### ISSUE THREAD

**Issue by calemccammon** [Hotride/OrionUO#121]
Orion version is: 1.0.0.0 (build Mar 28 2020 00:13:22) x64 bit

1. Open options menu
2. Select Profiles in Orion Configuration menu
3. Click 'Dupe from sel.' button
4. Observe nothing happens

Expected: New profile will show. It will have the same settings as the currently selected one.

**Comment by Hotride** [comment]
![image](https://user-images.githubusercontent.com/22247466/77963466-12b33380-72e6-11ea-8740-787319f48591.png)
You need to select profile (click on name, not use button) and press "Dupe from sel." button.
Perhaps this logic is not entirely correct and need to copy the current profile used.
