### ISSUE TITLE
Sphereserver, changing foundations dont delete the old ones.

### ISSUE THREAD

**Issue by AtillaG1** [Hotride/OrionUO#141]
Local
https://sphereserver.com/
Client: 7.0.90.0

Hi,
there is a minor issue with the foundation changing.
If i want to use different type foundation for the custom housing, the old type cannot be deleted and replaced, this way the other types are hidden under the original, since its thicker.

OrionUO
<a href="https://gyazo.com/de026185d7d35fc5067c5cb15f51f636"><img src="https://i.gyazo.com/de026185d7d35fc5067c5cb15f51f636.gif" alt="Image from Gyazo" width="794"/></a>

CUO
https://i.gyazo.com/0aa88449c3734b11bd8054b7f4b985ca.gif

**Comment by AtillaG1** [comment]
One addition, the commands for replacing are sphere internal, removeitem and additem.
The foundation type that cannot be removed in client is taken from multi, so maybe there is something in client that is blocking the original type to be hidden while removed by sphere?

**Comment by GladieUO** [comment]
fixed, thank you!
