### ISSUE TITLE
Staff animation is not the good one. 

### ISSUE THREAD

**Issue by Jhobean** [Hotride/OrionUO#143]
Orion client dont use ANIM Staff with staff (anim 648).
![image](https://user-images.githubusercontent.com/51728381/201484104-46e1bec9-b683-41e5-bb4a-2b8d2cab08ae.png)

When you have an layer 2 item equiped, It suppose to use walkStaff and RunStaff. This feature work correctyl with the torch (anim 501).

OSI client
![client_XhB2Wel3o5](https://user-images.githubusercontent.com/51728381/201484149-43a394de-30d6-4298-8da3-2249a7ad86d4.gif)

Orion Client
![OrionUO64_Oiy6YyH7H5](https://user-images.githubusercontent.com/51728381/201484153-7c17a247-1745-4aa9-896c-83d1c5b74269.gif)

**Comment by Nirad** [comment]
https://github.com/Hotride/OrionUO_SDL/blob/8623c573b848fca9ef1663466bd207ef05d32051/OrionUO/Managers/AnimationManager.cpp#L1866-L1894
Maybe here
