### ISSUE TITLE
Please add fallback for unknown effects/ animations

### ISSUE THREAD

**Issue by andrehsmendes** [Hotride/OrionUO#23]
Amazing project. Love the Orion client so far.

It is hard to play with Orion client when it keeps crashing on different visual effects, animation.

Would be great if was implemented a fallback in case the animation is not supported by just simple not showing it.

Regards

**Comment by AimedNuu** [comment]
It is the actually the case. I guess there's another weak spot in the code where null pointer exception gets thrown in the animation processing pipeline.
We have a bunch of crash reports, I'll add more checks.
