### ISSUE TITLE
Ghosts appear in war mode

### ISSUE THREAD

**Issue by Vlek** [Hotride/OrionUO#25]
When ghost players show themselves in game to the player, even though they're in war mode, they shouldn't appear to be so as per the regular client.

To replicate the issue, have a dead character enter and exit war mode in order to appear in front of a normal player character.

**Comment by AimedNuu** [comment]
It's not up to client to decide who's appearing and who's not. If server sends packets of a dead character when he enters war mode, client will draw his animation.

**Comment by Vlek** [comment]
That's not what I'm suggesting. What is happening is different from the normal client in that, when ghosts appear, it's because they're in war mode. However, they don't Appear to be in war mode in the regular client. I am stating that, if a character with the ghost graphic appears, then they should appear to not be in war mode.

**Comment by AimedNuu** [comment]
You're talking about the warmode animation, right?

**Comment by Vlek** [comment]
Correct. Ghosts should never appear to be in war mode to the player even though they technically are as that's the only state in which a player is going to see another player that is a ghost.

**Comment by AimedNuu** [comment]
All right, I'll fix it. It wasn't clear to me that you were talking about the animation in your initial report.

**Comment by AimedNuu** [comment]
Fixed in https://github.com/Hotride/OrionUO/commit/9a40da879bffb97a8813460f7110562b5f9e7212
