### ISSUE TITLE
Some in-game player messages do not turn gold on hover

### ISSUE THREAD

**Issue by Vlek** [Hotride/OrionUO#26]
I noticed this happening with some text but not others. The person that I had originally found this on had a very, very dark blue text color, and it did not highlight. Other people's worked fine, including their guild tags. I am unsure whether it had anything to do with the person, their gear (they were riding a tiger), or their text color.

**Comment by AimedNuu** [comment]
Were you zoomed in or out when this happened?

**Comment by AimedNuu** [comment]
I can not do anything with this issue. If you were zoomed in/out, then you should pay attention when you've enabled this. Zooming is  in beta and is not working properly when selecting/hovering over anything.
If this is something else, I need a way to reproduce this. We're not going waste our time looking for  a condition to trigger such a minor issue.
I'm closing this.

**Comment by Vlek** [comment]
I love how you just assumed I did a zoom, and wrote off the bug report as me wasting your time.

I wasn't zoomed in, or, at least, I had played with the option, turned it off, and have logged in and out several times without having turned it back on. If it could potentially still be zoomed, I would love to hear how to fix that.

Even so, regardless of a scaling issue, it's adding characters that aren't present in the item's name. That doesn't seem like a scaling issue unless you're doing something really wonky under the covers instead of just letting OpenGL take care of it.

**Comment by AimedNuu** [comment]
In your initial report you say that it's about hovering and highlighting and nothing about adding characters which shouldn't be there.

**Comment by AimedNuu** [comment]
Do you have a reproducible case for me?

**Comment by Vlek** [comment]
Sorry! You're right, that was another issue I was having. I am unsure whether this has to do with scaling, so go ahead and close it. I will see if I can get you a reproducible case. I witnessed this on UOGamer's Hybrid server from someone with dark, dark blue text, probably 0x0003.

**Comment by AimedNuu** [comment]
Np, if you mange to reproduce this feel free to reopen this.

**Comment by Vlek** [comment]
I had re-tested it, and had edited my previous message. I was able to reproduce it by changing my character's font color to 0x0003. I am unable to get the yellow highlight hue with that color for some reason.
