### ISSUE TITLE
Alt + j for journal menu

### ISSUE THREAD

**Issue by Vlek** [Hotride/OrionUO#27]
Alt + j is the standard button for opening the journal menu. I was unsure how to open it except through that button, so I am unsure whether the journal is even available.

**Comment by AimedNuu** [comment]
It's just a keybinding in client macros. Do you have it defined there? I have tested this a moment ago. If I create any keybinding, for example ( alt + j ) for open : journal macro, it works.

**Comment by Vlek** [comment]
What would that be in the API? Orion.ShowJournal, or is there the in-game one as well?

**Comment by AimedNuu** [comment]
Orion.ShowJournal(); is an Orion Assistant command and will show all journal text in a text box. I don't think that this is what you want.
If you want to open journal with Orion Assistant command you need to create a macro:
Orion.CreateClientMacro('Open', 'Journal').Play();

Or just do it the same way as you create a client macro in EA classic 2d client. Options -> Macro Options etc.
