### ISSUE TITLE
Missing DLL?

### ISSUE THREAD

**Issue by SakuraUO** [Hotride/OrionUO#3]
"The procedure entry point GetSystemDefaultLocaleName could not be located in the dynamic link library KERNEL32.dll."

That is what the error says upon opening "OrionUO.exe - Entry Point Not Found."

I'm using Windows XP SP3.

**Comment by Hotride** [comment]
Orion have some problems with starts on WinXP now.
http://bt.orion-client.online/view.php?id=65

**Comment by Hotride** [comment]
I fix problem with locale function, you can try start Orion on WinXP, but may still be a problem and it does not run.

**Comment by SakuraUO** [comment]
Thank you! I can now play.There's a little bit of lag, but I'm not concerned by that.
