### ISSUE TITLE
Skill decrease messages do not have a negative sign in them

### ISSUE THREAD

**Issue by Vlek** [Hotride/OrionUO#30]
When skills decrease in game, it states that they decreased, but it does not include a negative sign in the number.

**Comment by AimedNuu** [comment]
This message is being sent by server. It's not up to client.

**Comment by Vlek** [comment]
It's actually entirely up to the client. Just take a [look at this line](https://github.com/Hotride/OrionUO/blob/ad98e35cf7080ab32eba42a6b2ea8dc9a7302762/OrionUO/Managers/PacketManager.cpp#L2254). The number is always going to be a positive one, even on a decrease. Just do an absolute value of the change.

**Comment by AimedNuu** [comment]
Hmmm

**Comment by AimedNuu** [comment]
Im testing it on my local ServUO with T2A as expansion and I see negative numbers when I decrease my skills. 
Also, in the same link you gave me, you can see here:
`				float change = (float)(baseVal / 10.0f) - skill->BaseValue;

				if (change)
				{
					char str[128] = { 0 };
					sprintf_s(str, "Your skill in %s has %s by %.1f%%.  It is now %.1f%%.", skill->Name.c_str(), ((change < 0) ? "decreased" : "increased"), change, skill->BaseValue + change);
					//else if (change > 0) sprintf(str, "Your skill in %s has increased by %.1f%%.  It is now %.1f%%.", UO->m_Skills[id].m_Name.c_str(), change, obj->GetSkillBaseValue(id) + change);
					g_Orion.CreateTextMessage(TT_SYSTEM, 0, 3, 0x58, str);
				}
			}`

change variable is going to be a negative float number. Can you give me more info how and where you have encountered this?

**Comment by Vlek** [comment]
Just did an image search, [this is how I was expecting the output of that string to look like](https://imgur.com/3y4agVn).

So, even when it says that the user's skill decreased, it's a positive number.

**Comment by AimedNuu** [comment]
Okay, I'm all confused now xD
Orion does print this with with a minus, so as a negative number. But in your screenshot it looks like a positive number and it also looks like this is a screenshot from classic 2D client, am I right?

So I guess you meant the opposite in your initial post?

**Comment by Vlek** [comment]
Sorry, yes, that is what I meant. I was stating that I was expecting to happen, not the current state of OrionUO.

**Comment by AimedNuu** [comment]
Changed in https://github.com/Hotride/OrionUO/commit/5f77ed2fd2d5110a5fbb4fba7768f0bd6cc43684
