### ISSUE TITLE
Lowercase "L" added to clicked item's properties in Pre-AoS shards for blessed items

### ISSUE THREAD

**Issue by Vlek** [Hotride/OrionUO#31]
For some items, there's added output that's not present in the normal client. I noticed this when clicking items to get their name in Pre-AoS shards. It appears to be adding a lowercase "L" between the name and the "[Blessed]" for only blessed items. If it's blessed and exceptional, then it did not appear to happen.

The item name displays:

(item name)\
l\
[Blessed]

**Comment by AimedNuu** [comment]
Fixed in https://github.com/Hotride/OrionUO/commit/8f5199e
