### ISSUE TITLE
Mastery Books

### ISSUE THREAD

**Issue by gobeeels** [Hotride/OrionUO#54]
Mastery Book Implementation would be nice. Right now, if i click the Mastery Book, the normal Spellbook opens. Can´t use the Mastery Abilities too. Official Shards.

![grafik](https://user-images.githubusercontent.com/38256695/38569237-0ace128a-3ceb-11e8-9248-f7e2a68af198.png)

**Comment by Nic84** [comment]
I'm working on it, still need to add icons and change a bit how right page works but will be done!
