### ISSUE TITLE
Can't open gift Box

### ISSUE THREAD

**Issue by ghost** [Hotride/OrionUO#65]
Can't open box:

Server : EA/OSI
CliVer : 7.0.63.2

<a href="https://imgbb.com/"><img src="https://image.ibb.co/nJisdc/missinggump.png" alt="missinggump" border="0"></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/nu8NUH/box.png" alt="box" border="0"></a>
ID of bags in picture.

**Comment by Vlek** [comment]
Thank you for this, AimeedNuu said in the Discord that he was adding this as they were found. I know for a fact that there are more, like the heart-shaped box. Do you know the graphic for that one, too? For future reference, how did you find the graphic?

Also, if anyone has a problem opening this container in the future after it has been fixed, AimedNuu suggested that I delete the text files under UO Install Folder > OrionData as they are not updated with the client and contain these definitions. The Orion client will notice they're missing however, and will create them with the new definitions if you manually delete them.

**Comment by JulienThink** [comment]
I will provide it tomorrow. To get graphic I use _infotile command on OSI shard and it give the info.
AimedNuu fixed somes giftbox but he didnt had all list i think, that's why i try to provide what i can find =)
