### ISSUE TITLE
Stamina Block on Trammel/Ilshenar/Termur/Malas

### ISSUE THREAD

**Issue by ghost** [Hotride/OrionUO#68]
Server ; EA/OSI  and RunUO
CliVer : 7.0.63.2
It happens sometime when I walk on a mobile, the stamina block character.

**Comment by Nic84** [comment]
What do you mean? Ignore stamina check is not working?

**Comment by JulienThink** [comment]
yes but have to use assistant to ignore. so i guess it's bug related client?

**Comment by Pack4Duck** [comment]
I've same issue too
