### ISSUE TITLE
I press "Check New versions" and Nothing happens

### ISSUE THREAD

**Issue by siteincity** [Hotride/OrionUO#79]
Im install orion client from https://github.com/Hotride/OrionLauncher/blob/master/INSTALL/Orion%20Launcher_1.1.5.0.exe

Run.  And not work updates. Not work Accounts -> configure client version.

This is my first install this client

My System Parameters:
https://uorpg.net/
windows 7 maximal service pack 1
Video GForce GTS 250
RAM 6 GB

Я поставил клиент в папку C:\Orion Launcher. Программа запустилась, потребовала показать папку с ультимой, далее ничего не произошло и функции никакие не работают, просто жму на кнопки и ничего не происходит. Не работают обновления. Кнопка нажимается, становится не активной на 1-2 сек, далее опять активная. Но списки файлов никакие не появляются. Пробовал подключаться через Прокси или VPN. Не знаю что может быть
![11](https://user-images.githubusercontent.com/14177061/41356972-30c2a64a-6f36-11e8-9114-3be81b06befb.jpg)
![22](https://user-images.githubusercontent.com/14177061/41357096-6bd483f2-6f36-11e8-9b1f-b040cbbb6448.jpg)

**Comment by TorchwoodPL** [comment]
Maybe it's because https://orion-client.online/ is not working.

**Comment by Nic84** [comment]
You can still manually update from this website: http://www.orionuo.com/
