### ISSUE TITLE
[Question] Compile to javascript

### ISSUE THREAD

**Issue by MBoberski** [Hotride/OrionUO#80]
Is there a way to compile orion via http://kripken.github.io/emscripten-site/index.html or anything like that?

**Comment by AimedNuu** [comment]
It's not cross-platform...yet

**Comment by fungos** [comment]
But it will be possible once the SDL2 port is finished. There are two problems though:
 - Spectre/Meltdown security issues caused browsers to disable SharedArrayBuffer required to proper multi-threading support with Emscripten;
- UO data files should be accessed locally (copyright & technical issues);

In anyway, it will be possible someday but there is a long way to go.
