### ISSUE TITLE
Error while starting client

### ISSUE THREAD

**Issue by TorchwoodPL** [Hotride/OrionUO#81]
I have compiled Orion form latest commit and after getting all uo files I get, after I try to start client:

![Error](http://img.hyeah.eu/pic/41529398095.png)

It's the same when I create that file.

**Comment by fungos** [comment]
Bad error message. This means Orion couldn't find your UO files. (tip: fix your working directory on vidsual studio if you're trying to debug).
Fixed https://github.com/Hotride/OrionUO/commit/8fbd5537e3a790970ac667d4ed8bdb01d43fd7ba
