### ISSUE TITLE
osx/linux progress

### ISSUE THREAD

**Issue by pechorin** [Hotride/OrionUO#87]
Hello. Any success on linux/macosx port? Today i spent some time to fix build file and some compiling issues on osx and have some success — it compiles but crashes with segfault after Orion launch:

 LOG: INITIATING CAPPLICATION
 LOG: Mmaping  /Users/vorobey/uo/OrionUO/build/OrionUO/uo_debug.cfg
NOT_IMPLEMENTED: ../OrionUO/Stubs.cpp:12: GetSystemMetrics
NOT_IMPLEMENTED: ../OrionUO/Stubs.cpp:12: GetSystemMetrics
[1]    69497 segmentation fault  ./OrionUO

Can you help me with understanding about linux port progress? Big thanks

**Comment by fungos** [comment]
Hi, you can see the progress here: https://github.com/Hotride/OrionUO/projects/2
There aren't much to do, it is runnable on linux but with a lot of windowing/input issues still to be fixed.
I have doubts I'll be able to continue for at least 2 months yet, so any help is welcome and I can review and give directions on issues.
