### ISSUE TITLE
Client Freeze

### ISSUE THREAD

**Issue by Espcevan** [Hotride/OrionUO#95]
Not really sure what this issue might be but...
I'm using the stock 7.0.74.0 client with Orion, shouldn't be any issues right?
There are times I'm playing and i go to a certain place the staff have setup as a little town in green acres, and the client freezes up and i cant log back in unless i use UOSteam to move my guy away. It also happens when teleporting to Britt sometimes and once with Moonglow.

**Comment by Hotride** [comment]
Fixed.
The update is available in the launcher.
