### ISSUE TITLE
Vendor wrong label

### ISSUE THREAD

**Issue by Khaldor48** [Hotride/OrionUO#98]
http://prntscr.com/q1rwmn

Hello, I'm not sure if this was working correctly or not. But when I open vendor gump the picture and label is not correct. 

Picture is the item which I'm buying. The name of item is very strangely associated because it looks like it's randomly assigned. Sometimes it's event matching but mostly not. Thank you for you time.

**Comment by Hotride** [comment]
Hi, try updating Orion, in the latest version this should be fixed.

**Comment by Khaldor48** [comment]
Hi, thank you for fast response. 
It's still there after update:
![image](https://user-images.githubusercontent.com/22933400/69746500-ae6c4180-1144-11ea-8c64-b44b95c8b5bb.png)

**Comment by Hotride** [comment]
So, what is a server do you play?

**Comment by Khaldor48** [comment]
I'm creating my own server. It runs on Sphere 0.56d, client version 2.0.4a.

I can provide mul files if needed or create account if you want to explore it directly here. But web is the last thing I'll do right before server launch.

**Comment by Hotride** [comment]
Will be fixed in the next release.

**Comment by Khaldor48** [comment]
Nice work! It's alright now. Thank you!
